language: cpp
compiler: gcc
cache: apt

before_script:
 - sudo apt-get install qt4-qmake
 

 - wget -O boost_1_55_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.gz/download
 - tar xzvf boost_1_55_0.tar.gz
 - cd boost_1_55_0/
 - sudo apt-get update
 - sudo apt-get install build-essential g++ python-dev autotools-dev libicu-dev build-essential libbz2-dev 
 - ./bootstrap.sh --prefix=/usr/local
 - user_configFile=`find $PWD -name user-config.jam`
 - echo "using mpi ;" >> $user_configFile
 - n=`cat /proc/cpuinfo | grep "cpu cores" | uniq | awk '{print $NF}'`
 - sudo ./b2 --with=all -j $n install 
 - sudo sh -c 'echo "/usr/local/lib" >> /etc/ld.so.conf.d/local.conf'
 - sudo ldconfig

 - sudo apt-get install libgsl0-dev
 
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get -qq update
 - sudo apt-get -qq install gcc-4.8 g++-4.8
 
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90


 - g++ --version
 - gcc --version

 - chmod +x install
 - chmod u+w ~

script:
 - ./install
